name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache node modules and Cypress binary
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.cache/Cypress
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Build React App
      run: npm run build

    - name: Start the application server
      run: |
        nohup npm start &
        sleep 10 # Allow some time for the server to start

    - name: Run Cypress tests
      run: npx cypress run --browser "chrome"

    - name: Deploy to Azure SWA
      run: |
        echo "SWA_TOKEN=${{ secrets.DWINDLE_TOKEN }}" > .env
        npx swa deploy --env production --deployment-token ${{ secrets.DWINDLE_TOKEN }} ./build
